### ISSUE TITLE
在mac平台执行scons命令时出错

### ISSUE THREAD

**Issue by oskycar** [zlgopen/awtk-examples#1]
进入到HelloWorld-Demo目录中执行scons命令后，终端提示如下错误信息，似乎是文件内容编码有问题，试了其他几个例子目录也是这个错误：
`scons: Reading SConscript files ...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 5: invalid continuation byte:
  File "/Users/cbav/Downloads/allenyang/project/opensource/awtk/demo/awtk-examples/HelloWorld-Demo/SConstruct", line 14:
    sys.path.insert(0, getAwtkRoot())
  File "/Users/cbav/Downloads/allenyang/project/opensource/awtk/demo/awtk-examples/HelloWorld-Demo/SConstruct", line 7:
    for line in fo.readlines():
  File "/anaconda3/lib/python3.7/codecs.py", line 322:
    (result, consumed) = self._buffer_decode(data, self.errors, final)`

**Comment by sosotan** [comment]
可以临时把 assets_gen.bat文件中的所有注释行删除看看（@rem 开头的行）
我们后续会改进这个问题

**Comment by oskycar** [comment]
> 可以临时把 assets_gen.bat文件中的所有注释行删除看看（@rem 开头的行）
> 我们后续会改进这个问题

我自己写了个mac平台下的一个简单demo的cmake的编译环境，[https://github.com/oskycar/awtktest_cmake](https://github.com/oskycar/awtktest_cmake)
可以为你们的demo提供一份cmake编译配置，真的是很方便。

**Comment by sosotan** [comment]
感谢分享

**Comment by sosotan** [comment]
最新版本已经修正该问题
