### ISSUE TITLE
linux下运行界面显示异常

### ISSUE THREAD

**Issue by Jun1172** [zlgopen/awtk-examples#2]
如图所示，显示成了这样，我按照编译说明，执行了以下内容
请问怎么解决这个问题？
sudo apt-get install scons libsndio-dev libgtk-3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev git vim clang-format
scons
./bin/demoui

![ZH0(AOSZ5KWRPB(F XRF_ K](https://user-images.githubusercontent.com/49546239/61108118-15e66500-a4b4-11e9-9b68-f0aeaf14e422.png)

**Comment by WeSrc-Yin** [comment]
应该是你电脑不支持openGL，那么在awtk_config.py里面打开定义NANOVG_BACKEND='AGGE'就可以。@Jun1172

**Comment by sosotan** [comment]
用最新版本awtk，或者像楼上说的AGGE模式试试，因为默认是opengl模式，这种情况有时候是机器的opengl驱动不完善的问题
