### ISSUE TITLE
树莓派上编译智能手表项目运行出错（linux-fb方式）

### ISSUE THREAD

**Issue by xiaoyu-ebox** [zlgopen/awtk-examples#5]
内置例程运行ok，但智能手表的例程错误如下，请帮忙看看：

`pi@raspberrypi: $ ./release/bin/demoui 
app_root_is_valid:43 app_root != NULL
try /home/pi/work/awtk/awtk-linux-fb
try /home/pi/work/awtk/awtk-linux-fb/release/bin
app_root=/home/pi/work/awtk/awtk-linux-fb/release
fb_info_t: /dev/fb0
fb_info_t: xres=1920 yres=1080 bits_per_pixel=32 mem_size=8294400
fb_info_t: red(16 8) green(8 8) blue(0 8)
line_length=7680 mem_size=8294400 smem_len=8294400
xres_virtual =1920 yres_virtual=1080 xpanstep=1 ywrapstep=0
ratio=1.000000 1920 1080
Build at: Nov 13 2019 23:20:43
!!!Asset [name=preload type=ui] not exist!!!
ui_loader_load_widget:38 ui != NULL
!!!Asset [name=cursor type=image] not exist!!!
window_manager_default_set_cursor:1111 image_manager_get_bitmap(image_manager(), cursor, &bitmap) == RET_OK
!!!Asset [name=cursor type=image] not exist!!!
window_manager_paint_cursor:533 image_manager_get_bitmap(image_manager(), wm->cursor, &bitmap) == RET_OK
widget_lookup_all:786 widget != NULL && name != NULL
widget_lookup_all:786 widget != NULL && name != NULL
!!!Asset [name=earth type=image] not exist!!!
widget_set_value:195 widget != NULL
widget_set_text_utf8:248 widget != NULL
widget_lookup_all:786 widget != NULL && name != NULL
widget_lookup_all:786 widget != NULL && name != NULL
!!!Asset [name=dialog_title type=image] not exist!!!
widget_set_value:195 widget != NULL
widget_set_text_utf8:248 widget != NULL
widget_lookup_all:786 widget != NULL && name != NULL
widget_lookup_all:786 widget != NULL && name != NULL
!!!Asset [name=rgb type=image] not exist!!!
widget_set_value:195 widget != NULL
widget_set_text_utf8:248 widget != NULL
widget_lookup_all:786 widget != NULL && name != NULL
widget_lookup_all:786 widget != NULL && name != NULL
!!!Asset [name=rgba type=image] not exist!!!
widget_set_value:195 widget != NULL
widget_set_text_utf8:248 widget != NULL
widget_lookup_all:786 widget != NULL && name != NULL
widget_lookup_all:786 widget != NULL && name != NULL
!!!Asset [name=system_bar type=ui] not exist!!!
ui_loader_load_widget:38 ui != NULL
widget_factory_create_widget:82 iter != NULL
ui_builder_default_on_widget_start: not supported type gesture
demoui: build/var/awtk/src/ui_loader/ui_builder_default.c:43: ui_builder_default_on_widget_start: Assertion `!"not supported"' failed.
已放弃`

**Comment by sosotan** [comment]
我调试看看

**Comment by sosotan** [comment]
其他例子是否能正常运行？
如果要使用awtk-linux-fb运行awtk，需注意让树莓派运行在纯字符模式
你试试最新版本的awtk和awtk-linux-fb
