### ISSUE TITLE
使用AWTK Designer无法打开awtk-examples的布局文件

### ISSUE THREAD

**Issue by zhanglu993** [zlgopen/awtk-examples#6]
使用AWTK Designer无法打开awtk-examples的布局文件，是使用方式有问题还是本身demo工程本身就没有放此类文件
![image](https://user-images.githubusercontent.com/32049755/74239149-390b1880-4d12-11ea-94ea-e4d8f258f715.png)

**Comment by sosotan** [comment]
目前designer只能打开 HelloDesigner-Demo 这个工程，其他的demo还没有做designer的适配，近期会用designer重构这些demo
